### ISSUE TITLE
[BUG] Subaccount Admin Role collection throws error on destroy

### ISSUE THREAD

**Issue by cerpass-86LAK** [SAP/terraform-provider-btp#345] opened 2023-07-28 01:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of Terraform are you using?

0.2.0-beta

### What type of issue are you facing

bug report

### Describe the bug

Inconsistency with how subaccount admin is applied.
When creating the subaccount the user who created it is automatically given the role subaccount admin. 

The newly added data.subscriptions block throws an empty list when trying to view available entitlements, even though I should already have subaccount admin. 

```hcl
data "btp_subaccount_subscriptions" "all" {
  subaccount_id = btp_subaccount.subaccount.id
}

output "availableSubscriptions" {
  value = data.btp_subaccount_subscriptions.all
}
```

If I manually give myself subaccount admin using  
```hcl
resource "btp_subaccount_role_collection_assignment" "subaccountAdministrator" {
   for_each = var.subaccountAdmin
   subaccount_id        = btp_subaccount.subaccount.id
   role_collection_name = "Subaccount Administrator"
   user_name            = each.value
}
```

On a destroy it throws an error saying the last subaccount admin cannot be destroyed. 

![image](https://github.com/SAP/terraform-provider-btp/assets/124213814/dc4cf7e3-3d8b-42ab-a63b-c14bacd299a6)

Overall it is just inconsistent how subaccount admin is used across the different resource blocks. the first data block should work as I should by default have subaccount admin. If i manually give it to myself however, i can no longer destroy the environment as it throws the shown error.

**Comment by lechnerc77** [comment] 2023-07-28 07:00
@cerpass-86LAK concerning your remarks on the behavior:

- `When creating the subaccount the user who created it is automatically given the role subaccount admin.` - this is the default behavior and cannot be changed via the Terraform Provider.
- `On a destroy it throws an error saying the last subaccount admin cannot be destroyed.` - If I get your setup correctly you added yourself explicitly to the list of subaccount admins when setting up the account with the Terraform provider. Consequently, your user is stored in the state and the destroy tries to remove all admins from the subaccount. In real life this would lead to the customer being locked out from the subaccount. The platform therefore safeguards this situation by raising the error you experience. If the setup is done with a non-technical user you should keep this person out of the list of the subaccount admins (as the assignment is done implicitly by the platform) or you use a technical user for the setup and add the non-technical user via the approach you describe. In the later setup you must not remove the technical user from the subaccount as this would result in the same error.

I have a question concerning your remark on the data source `btp_subaccount_subscriptions`: This resource returns the app subscriptions that the subaccount is entitled to subscribe to. If you want to get the role collections a user is assigned to you would need to use the data source `btp_subaccount_user` (see [docu](https://registry.terraform.io/providers/SAP/btp/latest/docs/data-sources/subaccount_user)). Do I misunderstand what you want to achieve.

**Comment by v0lkc** [comment] 2023-07-28 08:40
Adding my thoughts on the behaviour of the `btp_subaccount_role_collection_assignment` resource. In my opinion it's a bug that the provider doesn't end up in error during `create` in case the user is already assigned. In fact terraform shall never automatically take over already existing resources into the state. If the practitioner wants to do it, he can trigger an `import` of the particular resource.

**Comment by aydin-ozcan** [comment] 2023-07-30 08:02
Hi @lechnerc77 , @v0lkc 

My experience with creating Kyma runtime may provide another perspective on this issue. After assigning the entitlements to the newly created subaccount, the creation of the Kyma environment instance block works, but Terraform returns an error:

> Error: API Error Creating Resource Environment Instance (Subaccount)
> 
> with btp_subaccount_environment_instance.kyma,
> on main.tf line 57, in resource "btp_subaccount_environment_instance" "kyma":
> 57: resource "btp_subaccount_environment_instance" "kyma" {
> 
> The user is unauthorized for this operation [Error: 11004/405].
> 

If I do nothing and just run `terraform apply` again, the Kyma environment starts to get created. However, I want to perform these operations in one `terraform apply`. So, I manually add my user to the subaccount admin role collection via `btp_subaccount_role_collection_assignment`, and then I can make it work in one `terraform apply`. But upon destruction, I get an error about "cannot delete the last admin user". To overcome this, I do some Terraform voodoo so that on destroy, the block about role assignment is not working because the subaccount is going to delete anyway. I don't know if @cerpass-86LAK  is also doing the role assignment manually like this.

**Comment by lechnerc77** [comment] 2023-07-31 06:08
@aydin-ozcan This sounds like a different issue to me. Can you open an issue with your Terraform files attached. Thanks!

**Comment by lechnerc77** [comment] 2023-08-01 06:13
@cerpass-86LAK Thanks for detailing the scenario. This helps a lot in analyzing the setup!

**Comment by lechnerc77** [comment] 2023-08-01 08:58
@cerpass-86LAK : I could (partially) reproduce your setup on a SAP BTP Trial account. 
Having said that I think this is not an issue with the assignment of the role collection to your user, but the data source is executed when the assignment of the entitlements is not yet finished:

![Screenshot 2023-08-01 103030](https://github.com/SAP/terraform-provider-btp/assets/22294087/2d5117ce-9c2e-4636-bab2-8b9fff701ab1)

In order to ensure the execution sequence it is necessary to put the data source into a module and then add a `depends on` statement to it. I have created some sample here that showcases this: <https://github.com/lechnerc77/retest-tfprovider-apps>.

With this setup I get the list of available app subscriptions without explicit assignment of the role collection. Please let me know if this fixes your issue.

**Comment by aydin-ozcan** [comment] 2023-08-01 10:54
@lechnerc77, your solution makes me want to try something else for my situation. 
I gave the entitlement creation block for Kyma runtime as a dependency to the environment instance creation block, and now I don't have to add myself explicitly to the admin. Kyma runtime creation started.
But it doesn't make sense, not just the error message "The user is unauthorized for this operation [Error: 11004/405]."
Also, why did it solve the issue when I added myself to the admin block separately?"
But it does explain why it worked in the second 'terraform apply'

**Comment by aydin-ozcan** [comment] 2023-08-01 11:17
Yes, it created the artificial delay, which is also what I was suspecting. But does this mean we should use depends_on to relate entitlement for every instance creation of service and subscriptions, not just the environment instance?

> With the next release, we should also include the configurable timeout, so that the creation of Kyma in one run is feasible with the provider.


Yes, this is something I am waiting for. I saw it in the next milestone makes me happy. For the time being, I use the provider locally and change the hardcoded timeout to 30 minutes. Wish I had requested it to be at least 30 minutes hardcoded before the beta 2 update so I could use the terraform registry version of the provider while waiting.

**Comment by lechnerc77** [comment] 2023-08-01 12:31
> @lechnerc77 , Yes, it created the artificial delay, which is also what I was suspecting. But does this mean we should use depends_on to relate entitlement for every instance creation of service and subscriptions, not just the environment instance?
> 
> > With the next release, we should also include the configurable timeout, so that the creation of Kyma in one run is feasible with the provider.
> 
> Yes, this is something I am waiting for. I saw it in the next milestone makes me happy. For the time being, I use the provider locally and change the hardcoded timeout to 30 minutes. Wish I had requested it to be at least 30 minutes hardcoded before the beta 2 update so I could use the terraform registry version of the provider while waiting.

Yes, you are right: if there are implicit dependencies between resources (like entitlement and service instance creation) you must use the `depends_on` option to inform Terraform about the execution sequence it should apply.

**Comment by 86LAK** [comment] 2023-08-03 01:27
@lechnerc77 Thanks for the response. I tested it out and the depends_on fixes my issue. Like @aydin-ozcan I got confused by the fact it worked when manually adding myself to subaccount admin. Thanks for the help and sorry for raising this.

**Closed** 2023-08-03 05:21 UTC
Labels: bug, btp-trial-account
