### ISSUE TITLE
[BUG] the plan_name attribute should not be required when creating subscriptions

### ISSUE THREAD

**Issue by Thanhphan1147** [SAP/terraform-provider-btp#342] opened 2023-07-27 12:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of Terraform are you using?

0.2.0-beta2

### What type of issue are you facing

bug report

### Describe the bug

In the BTP cli's documentation 

```
Parameters:
  --subaccount,-sa ID  The ID of the subaccount to subscribe to an application. Can be omitted if specified by 'btp target'.
  --to-app NAME        The name of the application to which to subscribe a subaccount.
  --plan NAME          (Optional) The plan of the multitenant application to subscribe to. You can omit this parameter if the multitenant application is in the current global account and only one plan was provided in the app configuration.
  --parameters JSON    (Optional) Additional parameters specified by the application provider. Enter in a valid JSON format as key-value pairs.
```

the --plan flag is marked as Optional, which is not the case in the resource's schema : https://github.com/SAP/terraform-provider-btp/blob/57f5054ad5349ea39c7dbd3b0c6fce84f428515e/internal/provider/resource_subaccount_subscription.go#L64C1-L65C1

This prevents subscription to services like IRPA which uses only app_name (plan_name = null)

### Steps To Reproduce

Create a subscription with Terraform using this configuration (the plan_name attribute not specified)

```HCL
resource "btp_subaccount_subscription" "sub" {
  subaccount_id = btp_subaccount.subaccount.id
  app_name = var.app_name
}
```

**Comment by lechnerc77** [comment] 2023-07-28 09:54
@Thanhphan1147 Just made another try to setup a global account with IRPA entitlement without a plan assigned which gives me the following message:

![Picture1](https://github.com/SAP/terraform-provider-btp/assets/22294087/a28d1e81-9ba2-4c4c-971f-ca52237633c3)

So currently not possible to reproduce your setup

**Comment by lechnerc77** [comment] 2023-08-01 08:41
The issue is caused in SAP internal setups. Alignment is that we keep the plan name required but fix the follow-up flow in the resource which currently cannot handle an empty plan name.
@Thanhphan1147 Thanks for your support and thanks for offering your support in delivering a fix for this. Highly appreciated

**Comment by Cocossoul** [comment] 2023-09-04 14:41
Hey there
Thanks a lot @lechnerc77 for the work and interest you have in this matter
I'm following up on Thanh's work, I just opened a pull request to propose his fix here= https://github.com/SAP/terraform-provider-btp/pull/404
Do you have an idea when this could be delivered ? It's a blocker for a feature in our team

**Comment by lechnerc77** [comment] 2023-09-05 13:28
@Cocossoul Thanks for your contribution. I will merge it into a branch where we can do the tests. After that we validate and merge it into main. I cannot say when it will be available there, as this issue is SAP-internal as far as we see and has lower priority than the issues necessary for our external customers.

As a workaround until the fix lands in the repo you can build the provider with the fix yourself and use it in your scenarios leveraging an override in the Terraform configuration.

**Closed** 2023-09-11 08:42 UTC
Labels: bug
