### ISSUE TITLE
[BUG] Unable to list service plans for a subaccount

### ISSUE THREAD

**Issue by iamdanielnemeth** [SAP/terraform-provider-btp#746] opened 2024-03-18 16:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

1.1.0

### What version of the Terraform CLI are you using?

1.3.0

### What type of issue are you facing

bug report

### Describe the bug

[Btp Subaccount Service Plans/(data.btp_subaccount_service_plans.all)] API Error\
    \ Reading Resource Service Plans (Subaccount) - json: cannot unmarshal string\
    \ into Go struct field ServicePlanMetadata.metadata.supportedPlatforms of type\
    \ []string\n"

**Comment by lechnerc77** [comment] 2024-03-18 20:48
@iamdanielnemeth can you please provide the Terraform configuration you are using.

**Comment by iamdanielnemeth** [comment] 2024-03-18 20:53
`
terraform {
      required_providers {
          btp = {
              source	= "SAP/btp"
              version = "1.1.0"
          }
      }
  }
  
provider "btp" {
    globalaccount = var.global_account_subdomain
    idtoken = var.idtoken
    cli_server_url = var.cli_server_url
}

 data "btp_subaccount_service_plans" "all" {
    subaccount_id = var.subaccount_id
}
 
  `

**Comment by vipinvkmenon** [comment] 2024-03-21 06:44
We have used your configuration and tried running it on productive landscapes, however we could not reproduce it.
Hence closing the ticket.

**Closed by vipinvkmenon** 2024-03-21 06:44 UTC
Labels: bug, needs-triage
