### ISSUE TITLE
[BUG] Directory Entitlement not working without user managment activated

### ISSUE THREAD

**Issue by RCarvalhoSiemens** [SAP/terraform-provider-btp#690] opened 2024-01-30 16:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

1.0.0 rc2

### What version of the Terraform CLI are you using?

1.7.1

### What type of issue are you facing

bug report

### Describe the bug

Altough the entitlements are being assigned to the directory, if the user managment is deactivated it still gives an authorization error message.
With the user managment activated it no longer gives the error message.
<img width="445" alt="TF issue" src="https://github.com/SAP/terraform-provider-btp/assets/144708058/2f1677c6-d2e5-44ec-97d0-6470cac927c6">

**Comment by lechnerc77** [comment] 2024-01-30 20:06
To be checked if related to #537.

**Comment by lechnerc77** [comment] 2024-01-31 06:30
@RCarvalhoSiemens Can you please provide the role collections assigned to the user for:

1. the setup that works
2. the setup that raises the error

**Comment by RCarvalhoSiemens** [comment] 2024-01-31 10:32
Hello @lechnerc77, the role collection assigned was the same on both setups, Subaccount Administrator

**Comment by lechnerc77** [comment] 2024-02-01 15:16
Fixed with #537 - available with release 1.0.0

**Closed by lechnerc77** 2024-02-01 15:16 UTC
Labels: bug, needs-triage

**Comment by RCarvalhoSiemens** [comment] 2024-02-01 15:59
Hello @lechnerc77, 

> @RCarvalhoSiemens: so no global account admin was assigned to the user? In case of user management on directory level. no directory admin role collection was assigned to the user that executed the script?

Global account admin was assigned to the user.
<img width="234" alt="image" src="https://github.com/SAP/terraform-provider-btp/assets/144708058/9e280a95-c880-4acc-b915-c879885afc8a">

I believe it is not the same problem as in #537 because I  the entitlements are added by terraform although I have the error message mentioned above

**Comment by lechnerc77** [comment] 2024-02-01 16:15
@RCarvalhoSiemens : I could not reproduce the issue with what is currently available in  the `main` branch.  
Can you share the Terraform configuration you are using for the overall setup, so that we can give that a shot?

**Comment by RCarvalhoSiemens** [comment] 2024-02-01 17:14
Sure, here you can find attached the file with the provider configuration as well as the directory entitlement part
[TF config & directory entitlements.txt](https://github.com/SAP/terraform-provider-btp/files/14128607/TF.config.directory.entitlements.txt)

**Comment by lechnerc77** [comment] 2024-02-02 07:26
@RCarvalhoSiemens Did another retest with the following configuration using the provider state of `main` = upcoming release:

```
resource "btp_directory" "dir_with_features" {
  name        = "my-feat-directory"
  description = "This is a directory with features."
  features    = ["DEFAULT", "ENTITLEMENTS"]
}

resource "btp_directory_entitlement" "alert_notification_service" {
  directory_id = btp_directory.dir_with_features.id
  service_name  = "alert-notification"
  plan_name     = "free"
}

resource "btp_subaccount" "my_project" {
  parent_id = btp_directory.dir_with_features.id
  name      = "Retest entitlement Issue"
  subdomain = "retest-issue-6690"
  region    = var.region
}
```

The user executing the script is globalaccount and subaccount admin.

No error appears when assigning the entitlement to the directory.
