### ISSUE TITLE
[BUG] API Error (Bad Request) when fetching a service plan by name

### ISSUE THREAD

**Issue by marcelschork** [SAP/terraform-provider-btp#391] opened 2023-08-24 14:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of Terraform are you using?

0.3.0-beta1

### What type of issue are you facing

bug report

### Describe the bug

When fetching a service plan by name like follows

```
data "btp_subaccount_service_plan" "by_name" {
  subaccount_id = "<subaccount_id>"
  name = "free"
  offering_name = "alert-notification"
}

```
I face the following API error.

![image](https://github.com/SAP/terraform-provider-btp/assets/63337737/f3423af0-ebf1-4573-8dc0-6d1bf76576e1)

I want to fetch a specific service plan to be able to create a service instance which acutally requires the service plan id. 

### Steps To Reproduce

Create a minimal tf project, copy the data source declaration and execute tf plan.

**Comment by lechnerc77** [comment] 2023-08-24 15:30
@marcelschork I have retested the data source with the minimal configuration shown above and could not reproduce the error. 
I also retested successfully it on SAP BTP trial with a different service due to availability.

Can you tell me:

- which type of BTP account you are using (PAYG, trial)
- if you configuration deviates from mine given above
- if your subaccount is entitled for the service and service plan

**Comment by marcelschork** [comment] 2023-08-25 08:07
@lechnerc77 
My bad...the service and plan above were not entitled for my subaccount. 
But my original problem is with the workzone service. I'm on a trial account (region ap21) and when trying to fetch the plan id of the workzone service I'm retrieving the API error above. Here is a small sample to reproduce the issue.

`main.tf`

```terraform
resource "btp_subaccount" "test" {
  name      = "serviceplantest"
  subdomain = "serviceplantest"
  region    = "ap21"
}

resource "btp_subaccount_entitlement" "workzone" {
  subaccount_id = btp_subaccount.test.id
  service_name  = "build-workzone-standard"
  plan_name     = "standard"
}

data "btp_subaccount_environments" "all" {
  subaccount_id = btp_subaccount.test.id
}

resource "null_resource" "cache_target_environment" {
  triggers = {
    label = [for env in data.btp_subaccount_environments.all.values : env if env.service_name == "cloudfoundry" && env.environment_type == "cloudfoundry"][0].landscape_label
  }
  lifecycle {
    ignore_changes = all
  }
}

resource "btp_subaccount_environment_instance" "cloudfoundry" {
  subaccount_id    = btp_subaccount.test.id
  name             = "testorg"
  environment_type = "cloudfoundry"
  service_name     = "cloudfoundry"
  plan_name        = "standard"
  landscape_label  = null_resource.cache_target_environment.triggers.label

  parameters = jsonencode({
    instance_name = "testorg"
  })
}

data "btp_subaccount_service_offerings" "all" {
  subaccount_id = btp_subaccount.test.id
  environment = "cloudfoundry"
  depends_on = [btp_subaccount_environment_instance.cloudfoundry, btp_subaccount_entitlement.workzone]
}

data "btp_subaccount_service_plans" "all" {
  subaccount_id = btp_subaccount.test.id
  environment = "cloudfoundry"
  depends_on = [btp_subaccount_environment_instance.cloudfoundry, btp_subaccount_entitlement.workzone]
}

data "btp_subaccount_service_plan" "by_name" {
  subaccount_id = btp_subaccount.test.id
  name = "build-workzone-standard"
  offering_name = "standard"
}

output "service-offerings" {
  value = data.btp_subaccount_service_offerings.all.values
}

output "service_plans" {
  value = data.btp_subaccount_service_plans.all.values
}

output "plan_id" {
  value = data.btp_subaccount_service_plan.by_name.id
}
```

`provider.tf``

```terraform

terraform {
  required_providers {
    btp = {
      source  = "sap/btp"
      version = "0.3.0-beta1"
    }
  }
}

provider "btp" {
  globalaccount = "<global_account_subdomain>"
}
```
Workzone is part of the fetched service offerings and the plan "standard" for the service is available and readable as well. I tried with several other services, there everything seems to be fine.

**Comment by lechnerc77** [comment] 2023-08-25 09:20
@marcelschork Can you check the technical name that is displayed in your entitlements for this service/app? In my trial (also on apj21) I have as technical name "SAPLaunchpad" for the SAP Build Workzone Standard Edition:

![Screenshot 2023-08-25 111804](https://github.com/SAP/terraform-provider-btp/assets/22294087/042b2e55-9030-4bc0-88c0-caf0febdc70f)

**Comment by marcelschork** [comment] 2023-08-25 14:15
![image](https://github.com/SAP/terraform-provider-btp/assets/63337737/e64d75ca-cd2a-4459-b1c3-69c1a4b5ee5c)

"SAPLaunchpad" is the one I'm searching for. I entitled "build-workzone-standard" by accident. So my problem is solved and I was able to subscribe to the Launchpad service after the entitlement successfully, thank you! 

But the problem with this second service with technical name "build-workzone-standard" and plan "standard" still exists. What confuses me is the fact that in your screenshot the service with the technical name "SAPLaunchpad" contains two plans and in my case it's two service with one plan each.

**Comment by lechnerc77** [comment] 2023-08-26 08:37
That confuses me too. I will catch up with the Build workzone team what this new entry is all about. I leave the issue open and will give an update here, but will label it that here is nothing to fix from TF provider side

**Comment by lechnerc77** [comment] 2023-08-28 07:29
@marcelschork The error arises as the other service is only available in a Cloud Foundry environment. It is a service that allows access to interact with the workzone service via API.

Unfortunately this is not visible in the cockpit except for the fact that you do not see it in the marketplace when you do not have a Cloud Foundry environment active.

The error shown in the provider  is propagated from the BTP CLI however this needs to be improved. We have an issue open for that (#30 ) and I will therefore close this issue

**Closed by lechnerc77** 2023-08-28 07:29 UTC
Labels: bug, out-of-scope
